name: AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

permissions:
  contents: read

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc:
    uses:
      ./.github/workflows/intel.yml
  intel:
    uses:
      ./.github/workflows/gcc.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo "hello world"
        run: |
          echo "hello world"